package com.myproject.model;

import java.time.LocalDate;

import jakarta.persistence.*;

@Entity
@Table(name = "shift_plan")
public class ShiftPlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String department;
    private String staffName;
    private String role; // Doctor / Nurse / Technician
    private LocalDate date;

    private String shift; // Morning / Evening / Night
    private boolean aiRecommended; // true if generated by AI
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getStaffName() {
		return staffName;
	}
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
	public LocalDate getDate() {
		return date;
	}
	public void setDate(LocalDate date) {
		this.date = date;
	}
	public String getShift() {
		return shift;
	}
	public void setShift(String shift) {
		this.shift = shift;
	}
	public boolean isAiRecommended() {
		return aiRecommended;
	}
	public void setAiRecommended(boolean aiRecommended) {
		this.aiRecommended = aiRecommended;
	}
}
